export const hackImages = [
  // HACK FOLDER - Images
  'imgs/hack/andadeProofOfPurchase.png',
  'imgs/hack/Cyborg_video.png',
  'imgs/hack/elEstor_protest.png',
  'imgs/hack/emailLeak.png',
  'imgs/hack/filipino-hacktivists-destroy-technology-agency-servers-showcase_image-1-a-24790.jpg',
  'imgs/hack/Fin_dela_milicia.png',
  'imgs/hack/Fin_dela_mina.png',
  'imgs/hack/FotoEstor.png',
  'imgs/hack/hack_back.jpg',
  'imgs/hack/image.png',
  'imgs/hack/indigenous_walk.jpg',
  'imgs/hack/internal_workplan_leaked.png',
  'imgs/hack/mining_secret_HIV_AIDS.png',
  'imgs/hack/oil_protest.jpg',
  'imgs/hack/peruvian_protest.jpg',
  'imgs/hack/philippines_hack.jpg',
  'imgs/hack/Pronico_post_hack.png',
  'imgs/hack/redRiver_fenix.png',
  'imgs/hack/Screenshot 2026-02-17 154233.png',
  'imgs/hack/Screenshot 2026-02-17 154401.png',
  'imgs/hack/standing_rock.jpg',
  'imgs/hack/wakamaya.png',
  'imgs/hack/waterWay_Guatemala.png',
  
  // ARCHIVE_IMGS FOLDER - All archive images
  'imgs/archive_imgs/alcatraz.jpg',
  'imgs/archive_imgs/AMI_CrowDog.jpg',
  'imgs/archive_imgs/arctic_precolonial.jpg',
  'imgs/archive_imgs/colonial_1.jpg',
  'imgs/archive_imgs/colonial_2.jpg',
  'imgs/archive_imgs/dapl_proposed_route-650x508.jpg',
  'imgs/archive_imgs/DAPL_Sioux.jpg',
  'imgs/archive_imgs/DefendTheSacre.png',
  'imgs/archive_imgs/HudsonRiver_Precolonial.jpg',
  'imgs/archive_imgs/International_PoliticalPrisonerDay.jpg',
  'imgs/archive_imgs/July26KXLMarch_collage-650x433.jpg',
  'imgs/archive_imgs/JumpingBullRanch.jpg',
  'imgs/archive_imgs/Leaving_woundedKnee.jpg',
  'imgs/archive_imgs/LongestWalk.jpg',
  'imgs/archive_imgs/Missouri_Colonial.jpg',
  'imgs/archive_imgs/ncarsm_protestcollege.jpg',
  'imgs/archive_imgs/newspaper_trailofbrokentreaties.jpg',
  'imgs/archive_imgs/nodapl_crowd_closeup.jpg',
  'imgs/archive_imgs/pbs_woundedknee.jpg',
  'imgs/archive_imgs/precolonial_nature.jpg',
  'imgs/archive_imgs/protesters_takeoverBPA_1975_400pxw.jpg',
  'imgs/archive_imgs/Puerto_ricoIndependenceMovement.jpg',
  'imgs/archive_imgs/SFPeaksAerials-JOHN-RUNNING-650x432.jpg',
  'imgs/archive_imgs/spain_colonial_freeWomen.jpg',
  'imgs/archive_imgs/Steve_Robideau.jpg',
  'imgs/archive_imgs/sundance_indigenous.jpg',
  'imgs/archive_imgs/TradingPost.jpg',
  'imgs/archive_imgs/White-Buffalo-Girl-ceremony-tdih-768x512.jpg',
];

// VIDEOS for the corridor (these will be loaded as VideoTextures)
export const hackVideos = [
  'imgs/hack/hack_video.mp4',
  'imgs/hack/guacamaya_animalProtest.mp4',
];

// BACKGROUND VIDEO (plays on all walls: front, back, left, right, above)
export const hackBackgroundVideo = 'imgs/hack/hackDIY.mp4';
