export const hackImages = [
  // HACK FOLDER - Images
  'imgs/hack/andadeProofOfPurchase.png',
  'imgs/hack/Cyborg_video.png',
  'imgs/hack/elEstor_LakeIzabel.png',
  'imgs/hack/elEstor_protest.png',
  'imgs/hack/elEstor_Protest2.jpg',
  'imgs/hack/elEstor_Protest3.jpg',
  'imgs/hack/el_estorProtest1.png',
  'imgs/hack/emailLeak.png',
  'imgs/hack/Fin_dela_milicia.png',
  'imgs/hack/Fin_dela_mina.png',
  'imgs/hack/FotoEstor.png',
  'imgs/hack/hack_back.jpg',
  'imgs/hack/image.png',
  'imgs/hack/indigenous_walk.jpg',
  'imgs/hack/internal_workplan_leaked.png',
  'imgs/hack/mining_secret_HIV_AIDS.png',
  'imgs/hack/oil_protest.jpg',
  'imgs/hack/peruvian_protest.jpg',
  'imgs/hack/Pronico_post_hack.png',
  'imgs/hack/redRiver_fenix.png',
  'imgs/hack/Screenshot 2026-02-17 154233.png',
  'imgs/hack/Screenshot 2026-02-17 154401.png',
  'imgs/hack/standing_rock.jpg',
  'imgs/hack/wakamaya.png',
  
  // ARCHIVE_IMGS FOLDER - All archive images
  'imgs/archive_imgs/80sResidentialSchoolProtest.jpeg',
  'imgs/archive_imgs/991714868805867_ayer_mseeingIndianChicago.jpg',
  'imgs/archive_imgs/alcatraz.jpg',
  'imgs/archive_imgs/AMI_CrowDog.jpg',
  'imgs/archive_imgs/amongtheDullKnife.jpg',
  'imgs/archive_imgs/arcticClimateChangeProtest.jpg',
  'imgs/archive_imgs/arctic_precolonial.jpg',
  'imgs/archive_imgs/bangBang_NatalieBall.jpg',
  'imgs/archive_imgs/BuffaloHuntInSnow_GeorgeCatlin.png',
  'imgs/archive_imgs/circleOfLife_QavavauManumie.jpg',
  'imgs/archive_imgs/dapl_proposed_route-650x508.jpg',
  'imgs/archive_imgs/DAPL_Sioux.jpg',
  'imgs/archive_imgs/DefendTheSacre.png',
  'imgs/archive_imgs/dickBancroftUN.jpg',
  'imgs/archive_imgs/dickBancroftUN2.jpg',
  'imgs/archive_imgs/fishingOnColumbianRiver.jpg',
  'imgs/archive_imgs/ghostDance.jpg',
  'imgs/archive_imgs/ghostDance1.jpg',
  'imgs/archive_imgs/ghostDanceDrum_1890s.jpg',
  'imgs/archive_imgs/gwichin_SteeringCommitee.png',
  'imgs/archive_imgs/indianInTransition.jpg',
  'imgs/archive_imgs/International_PoliticalPrisonerDay.jpg',
  'imgs/archive_imgs/JumpingBullRanch.jpg',
  'imgs/archive_imgs/lakotaHorseman.jpg',
  'imgs/archive_imgs/Leaving_woundedKnee.jpg',
  'imgs/archive_imgs/LongestWalk.jpg',
  'imgs/archive_imgs/Missouri_Colonial.jpg',
  'imgs/archive_imgs/mohawkLand.jpg',
  'imgs/archive_imgs/mohawkOkaCrisis.jpg',
  'imgs/archive_imgs/motherEarth_ChrisPappan.jpg',
  'imgs/archive_imgs/napiDrum.jpg',
  'imgs/archive_imgs/nativeHostforWashingtonDC_EdgarHeapOfBirds.jpg',
  'imgs/archive_imgs/ncarsm_protestcollege.jpg',
  'imgs/archive_imgs/newspaper_trailofbrokentreaties.jpg',
  'imgs/archive_imgs/nodapl_crowd_closeup.jpg',
  'imgs/archive_imgs/parrotsPrayerSong_LindaLomahaftewa.jpg',
  'imgs/archive_imgs/pbs_woundedknee.jpg',
  'imgs/archive_imgs/portraitOfThomasinaEJordan.jpg',
  'imgs/archive_imgs/precolonial_nature.jpg',
  'imgs/archive_imgs/protesters_takeoverBPA_1975_400pxw.jpg',
  'imgs/archive_imgs/protestPines.jpg',
  'imgs/archive_imgs/Puerto_ricoIndependenceMovement.jpg',
  'imgs/archive_imgs/Quito-Bulletin-1A-400x516.jpg',
  'imgs/archive_imgs/Quito-Columbus.jpg',
  'imgs/archive_imgs/Quito-Pic-My-7.jpg',
  'imgs/archive_imgs/ravenStealstheSun_PresontSingeltary.jpg',
  'imgs/archive_imgs/redCloud_War.jpg',
  'imgs/archive_imgs/Steve_Robideau.jpg',
  'imgs/archive_imgs/sundance_indigenous.jpg',
  'imgs/archive_imgs/thuleCulture.jpg',
  'imgs/archive_imgs/TradingPost.jpg',
  'imgs/archive_imgs/turnOfTheCenturyDandy.jpg',
  'imgs/archive_imgs/utesHomelands_kayWalkingStick.jpg',
  'imgs/archive_imgs/weWereChildren_ResidentialSchools.jpg',
  'imgs/archive_imgs/White-Buffalo-Girl-ceremony-tdih-768x512.jpg',
  'imgs/archive_imgs/womenWoundedKnee.jpg',
  'imgs/archive_imgs/woundedKneeFlag.jpg',
  'imgs/archive_imgs/woundedKneeHorses.jpg',
  'imgs/archive_imgs/woundedKneeNegotiations.jpg',
  'imgs/archive_imgs/zapatista.png',
];

// VIDEOS for the corridor (these will be loaded as VideoTextures)
export const hackVideos = [
  'imgs/hack/hack_video.mp4',
  'imgs/hack/guacamaya_animalProtest.mp4',
];

// BACKGROUND VIDEO (plays on all walls: front, back, left, right, above)
export const hackBackgroundVideo = 'imgs/hack/hackDIY.mp4';
