export const hackImages = [
  'imgs/hack/archive.jpg',
  'imgs/hack/binary.gif',
  'imgs/hack/earth.jpg',
  'imgs/hack/filipino-hacktivists-destroy-technology-agency-servers-showcase_image-1-a-24790.jpg',
  'imgs/hack/hack_1.jpg',
  'imgs/hack/hack_back.jpg',
  'imgs/hack/image.png',
  'imgs/hack/indigenous_protest.jpg',
  'imgs/hack/indigenous_walk.jpg',
  'imgs/hack/love_letter.jpg',
  'imgs/hack/oil_protest.jpg',
  'imgs/hack/peruvian_protest.jpg',
  'imgs/hack/philippines_hack.jpg',
  'imgs/hack/pixel_art.png',
  'imgs/hack/screen.gif',
  'imgs/hack/Screenshot 2026-02-17 154233.png',
  'imgs/hack/Screenshot 2026-02-17 154401.png',
  'imgs/hack/standing_rock.jpg',
  'imgs/hack/the_fatrat.jpg',
  'imgs/hack/virus.gif',
  'imgs/hack/wakamaya.png',
  'imgs/hack/wifi_cracker.jpg',
];
